// This file will be auto-generated by Supabase CLI
// Run: supabase gen types typescript --local > packages/shared/src/database.types.ts

export type Database = {
  public: {
    Tables: {
      teams: {
        Row: {
          id: string;
          name: string;
          owner: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          owner: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          owner?: string;
          created_at?: string;
        };
      };
      // Add other tables as needed
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
};